### ISSUE TITLE
TypeError: Cannot read property 'extractor' of undefined

### ISSUE THREAD

**Issue by thariddler** [FullHuman/postcss-purgecss#15]
Using Tailwind and Vue webpack starter

```js
class TailwindExtractor {
  static extract(content) {
    return content.match(/[A-z0-9-:\/]+/g) || [];
  }
}
module.exports = {
  plugins: [
    tailwindcss('./tailwind.js'),
    require('autoprefixer')(),
    purgecss({
      content: [
        './src/**/*.html',
        './src/**/*.vue',
        './src/**/*.styl'
      ],
      extractors: [
        {
          extractor: TailwindExtractor,
          extensions: ["html", "js", "vue"]
        }
      ]
    })
  ]
}
```

What's the problem?

**Comment by SirNavith** [comment]
Hi, what I believe is happening is that you have a file in the glob done in the `content` array that does not have an accompanying extractor. I suspect it's the `.styl` files because they are not included in the `extensions` for the `TailwindExtractor`. 

Since I just learned from a Google search that `.styl` is Stylus, a CSS pre-processing language, you should exclude it from your `content` array because it is not HTML-like. This should fix your problem -- but I'm sorry if it doesn't because this is just the knowledge I got from solving a similar problem for myself.
